AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  iguala

  Sample SAM Template for iguala

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 45
  Api:
    Cors:
      AllowMethods: "'OPTIONS,POST,GET'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  LoginFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: login/
      Handler: login.app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        LoginFunction:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /iguala/login
            Method: post
  CreateAdminFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: create_admin/
      Handler: create_admin.app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        CreateAdminFunction:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /iguala/create_admin
            Method: post

  SaveLicenciaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: save_licencia/
      Handler: save_licencia.app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        SaveLicenciaFunction:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /iguala/save_licencia
            Method: post

  ConsultaCurpFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: search_curp/
      Handler: search_curp.app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        ConsultaCurpFunction:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /iguala/search_curp
            Method: get

  ConsultaTramiteFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: search_tramite/
      Handler: search_tramite.app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        ConsultaTramiteFunction:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /iguala/search_tramite
            Method: get

  ConsultaCpFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: search_cp/
      Handler: search_cp.app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        ConsultaCpFunction:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /iguala/search_cp
            Method: get

  SavePermisoComercioFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: save_permiso_comercial/
      Handler: save_permiso_comercial.app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        SavePermisoComercioFunction:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /iguala/save_permiso_comercial
            Method: post

  SearchLicenciaPublicFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: search_licencia_public/
      Handler: search_licencia_public.app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        SearchLicenciaPublicFunction:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /iguala/search_licencia_public
            Method: get

  UploadFileFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: s3_upload/
      Handler: s3_upload.app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        UploadFileFunction:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /iguala/s3_upload
            Method: get


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LoginApi:
    Description: "API Gateway endpoint URL for Prod stage for login function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/login/"
  LogindFunction:
    Description: "Login Lambda Function ARN"
    Value: !GetAtt LoginFunction.Arn
  LoginFunctionIamRole:
    Description: "Implicit IAM Role created for login World function"
    Value: !GetAtt LoginFunctionRole.Arn
  CreateAdminApi:
    Description: "API Gateway endpoint URL for Prod stage for create_admin function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/create_admin/"
  CreateAdminFunction:
      Description: "Login Lambda Function ARN"
      Value: !GetAtt CreateAdminFunction.Arn
  CreateAdminFunctionIamRole:
      Description: "Implicit IAM Role created for login World function"
      Value: !GetAtt CreateAdminFunction.Arn


  SaveLicenciaApi:
    Description: "API Gateway endpoint URL for Prod stage for create_admin function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/save_licencia/"
  SaveLicenciaFunction:
      Description: "Login Lambda Function ARN"
      Value: !GetAtt SaveLicenciaFunction.Arn
  SaveLicenciaFunctionIamRole:
      Description: "Implicit IAM Role created for login World function"
      Value: !GetAtt SaveLicenciaFunction.Arn

  ConsultaCurpApi:
    Description: "API Gateway endpoint URL for Prod stage for create_admin function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/search_curp/"
  ConsultaCurpFunction:
    Description: "Login Lambda Function ARN"
    Value: !GetAtt ConsultaCurpFunction.Arn
  ConsultaCurpFunctionIamRole:
    Description: "Implicit IAM Role created for login World function"
    Value: !GetAtt ConsultaCurpFunction.Arn


  ConsultaTramiteApi:
    Description: "API Gateway endpoint URL for Prod stage for create_admin function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/search_tramite/"
  ConsultaTramiteFunction:
    Description: "Login Lambda Function ARN"
    Value: !GetAtt ConsultaTramiteFunction.Arn
  ConsultaTramiteFunctionIamRole:
    Description: "Implicit IAM Role created for login World function"
    Value: !GetAtt ConsultaTramiteFunction.Arn

  ConsultaCpApi:
    Description: "API Gateway endpoint URL for Prod stage for create_admin function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/search_cp/"
  ConsultaCpFunction:
    Description: "Login Lambda Function ARN"
    Value: !GetAtt ConsultaCpFunction.Arn
  ConsultaCpFunctionIamRole:
    Description: "Implicit IAM Role created for login World function"
    Value: !GetAtt ConsultaCpFunction.Arn

  SavePermisoComercioApi:
    Description: "API Gateway endpoint URL for Prod stage for create_admin function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/save_permiso_comercial/"
  SavePermisoComercioFunction:
      Description: "Login Lambda Function ARN"
      Value: !GetAtt SavePermisoComercioFunction.Arn
  SavePermisoComercioFunctionIamRole:
      Description: "Implicit IAM Role created for login World function"
      Value: !GetAtt SavePermisoComercioFunction.Arn

  SearchLicenciaPublicApi:
    Description: "API Gateway endpoint URL for Prod stage for create_admin function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/search_licencia_public/"
  SearchLicenciaPublicFunction:
      Description: "Login Lambda Function ARN"
      Value: !GetAtt SearchLicenciaPublicFunction.Arn
  SearchLicenciaPublicFunctionIamRole:
      Description: "Implicit IAM Role created for login World function"
      Value: !GetAtt SearchLicenciaPublicFunction.Arn


  UploadFileApi:
    Description: "API Gateway endpoint URL for Prod stage for create_admin function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/s3_upload/"
  UploadFileFunction:
      Description: "Login Lambda Function ARN"
      Value: !GetAtt UploadFileFunction.Arn
  UploadFileFunctionIamRole:
      Description: "Implicit IAM Role created for login World function"
      Value: !GetAtt UploadFileFunction.Arn
