AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  iguala

  Sample SAM Template for iguala

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 45

Resources:
  LoginFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: login/
      Handler: login.app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        LoginFunction:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /iguala/login
            Method: post
  CreateAdminFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: create_admin/
      Handler: create_admin.app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        CreateAdminFunction:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /iguala/create_admin
            Method: post

  SaveLicenciaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: save_licencia/
      Handler: save_licencia.app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        SaveLicenciaFunction:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /iguala/save_licencia
            Method: post

  ConsultaCurpApi:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: search_curp/
      Handler: search_curp.app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        ConsultaCurpFunction:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /iguala/search_curp
            Method: get


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LoginApi:
    Description: "API Gateway endpoint URL for Prod stage for login function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/login/"
  LogindFunction:
    Description: "Login Lambda Function ARN"
    Value: !GetAtt LoginFunction.Arn
  LoginFunctionIamRole:
    Description: "Implicit IAM Role created for login World function"
    Value: !GetAtt LoginFunctionRole.Arn

  CreateAdminApi:
    Description: "API Gateway endpoint URL for Prod stage for create_admin function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/create_admin/"
  CreateAdminFunction:
      Description: "Login Lambda Function ARN"
      Value: !GetAtt CreateAdminFunction.Arn
  CreateAdminFunctionIamRole:
      Description: "Implicit IAM Role created for login World function"
      Value: !GetAtt CreateAdminFunction.Arn


  SaveLicenciaApi:
    Description: "API Gateway endpoint URL for Prod stage for create_admin function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/save_licencia/"
  SaveLicenciaFunction:
      Description: "Login Lambda Function ARN"
      Value: !GetAtt SaveLicenciaFunction.Arn
  SaveLicenciaFunctionIamRole:
      Description: "Implicit IAM Role created for login World function"
      Value: !GetAtt SaveLicenciaFunction.Arn

  ConsultaCurpApi:
    Description: "API Gateway endpoint URL for Prod stage for create_admin function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/search_curp/"
  ConsultaCurpFunction:
    Description: "Login Lambda Function ARN"
    Value: !GetAtt ConsultaCurpFunction.Arn
  ConsultaCurpFunctionIamRole:
     Description: "Implicit IAM Role created for login World function"
     Value: !GetAtt ConsultaCurpFunction.Arn
